### ISSUE TITLE
Allow negative strength for Set Terrain brush

### ISSUE THREAD

**Issue by Anarchid** [gajop/Scenario-Editor-Core#81]
The Set Terrain brush is an awesome thing for drawing terrain to specific altitude!

However, the most specific altitude i want has a value of -6, a magical value in ZK at which ground units and most naval units become nearly equal.

But Set Terrain brush is clipped to zero, so i'm reduced to sadness.

**Comment by gajop** [comment]
6 + Right click.
Closing for now, but seems like people are getting confused by this so might change it later on.

**Comment by Orfelius** [comment]
umh one question: is there also "retract" functionality for "add"?

**Comment by gajop** [comment]
What does retract mean? You can use right click with add heightmap too, which will basically subtract instead.

**Comment by Anarchid** [comment]
Oh, right click is inverse brush? So right-painting with Set +6 equals Set -6, and RMB with Add 10 is actually Sub 10.

Awesome!

**Comment by gajop** [comment]
Yes, I think it's good to have a "reverse effect" function happen on RMB, and it should be consistent in operations. It makes sense to have it for Add and Set, slightly less sense for Smooth and nearly no sense for the Texture painting.
The problem it's not intuitive (nobody thinks of -6 as Reverse 6), so I need to figure out a way to configure it, but maybe even allowing people to just specify negative values (will have to consider this).

**Comment by Anarchid** [comment]
I think the typical UI language for reversed operations (e.g. how blender sculpt tools do it) is Ctrl+LMB; also reverse smooth totally makes sense by being 'contrast'.
