### ISSUE TITLE
Exported heightmap is in red into black RGB instead of greyscale

### ISSUE THREAD

**Issue by Orfelius** [gajop/Scenario-Editor-Core#84]
![heightmap](https://cloud.githubusercontent.com/assets/9469212/8427501/2743306a-1f18-11e5-8fe7-db7929619da0.png)

**Comment by gajop** [comment]
this is fixed in the dev version of spring (i can confirm it works in 557 and probably newer versions too)

**Comment by Orfelius** [comment]
The weirdest thing is that it actually still works properly.

**Comment by gajop** [comment]
I've no idea why. Code was written for the newer engine features so it's actually a bit surprising to see it produce something meaningful. Anyway, dev engine is the way to go.
